environment:
  matrix:
    - PYTHON: "C:\\Python38-x64"
      PYTHON_VERSION: "3.8.20"
      PYTHON_ARCH: "64"

    - PYTHON: "C:\\Python39-x64"
      PYTHON_VERSION: "3.9.25"
      PYTHON_ARCH: "64"

    - PYTHON: "C:\\Python310-x64"
      PYTHON_VERSION: "3.10.20"
      PYTHON_ARCH: "64"

    - PYTHON: "C:\\Python311-x64"
      PYTHON_VERSION: "3.11.15"
      PYTHON_ARCH: "64"

    - PYTHON: "C:\\Python312-x64"
      PYTHON_VERSION: "3.12.13"
      PYTHON_ARCH: "64"

    - PYTHON: "C:\\Python313-x64"
      PYTHON_VERSION: "3.13.13"
      PYTHON_ARCH: "64"

    - PYTHON: "C:\\Python314-x64"
      PYTHON_VERSION: "3.14.15"
      PYTHON_ARCH: "64"

install:
  - SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%
  - pip install nose2
  - pip install coverage

build_script:
  - python nose2 -c nose2.cfg
