environment:
  matrix:
    - PYTHON: "C:\\Python310-x64"
      PYTHON_VERSION: "3.10.20"
      PYTHON_ARCH: "64"

    - PYTHON: "C:\\Python311-x64"
      PYTHON_VERSION: "3.11.15"
      PYTHON_ARCH: "64"

    - PYTHON: "C:\\Python312-x64"
      PYTHON_VERSION: "3.12.13"
      PYTHON_ARCH: "64"

    - PYTHON: "C:\\Python313-x64"
      PYTHON_VERSION: "3.13.13"
      PYTHON_ARCH: "64"

    - PYTHON: "C:\\Python314-x64"
      PYTHON_VERSION: "3.14.15"
      PYTHON_ARCH: "64"

install:
  - powershell -ExecutionPolicy ByPass -c "irm https://astral.sh/uv/0.11.17/install.ps1 | iex"
  - set Path=%USERPROFILE%\.local\bin;%Path%

build_script:
  - uv run --python %PYTHON_VERSION% --with nose2 --with coverage nose2 -c nose2.cfg --with-doctest
